# Alacritty Configuration File
# Configuração otimizada para produtividade e estética.

[general]
# Importa o tema Gruvbox Dark para uma melhor experiência visual.
import = ["~/.config/alacritty/themes/themes/gruvbox-dark.yml"]

[colors]
primary = { background = "#1A1715", foreground = "#ebdbb2" }

[env]
# Configuração do terminal para suporte a cores estendidas.
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 14

offset = { x = 1, y = 4 }

# Ajuste fino do posicionamento da fonte na renderização.
glyph_offset = { x = 0, y = 2 }

# Descomente e ajuste se precisar refinar ainda mais o alinhamento dos glifos.
[window]
title = "Alacritty"                        # Define um título base com ícone
dynamic_title = true                       # Permite que o título mude dinamicamente
dimensions = { columns = 160, lines = 35 } # Dimensões iniciais da janela do terminal.

# Adiciona um leve espaçamento nas bordas internas da janela.
padding = { x = 1, y = 1 }
dynamic_padding = true     # Ajusta automaticamente conforme necessário.

# Configuração das bordas e aparência da janela.
decorations = "full"      # Usa todas as decorações da janela (barra de título, bordas, etc).
startup_mode = "Windowed" # Inicia em modo de janela.

# Ajuste de transparência e efeitos visuais.
opacity = 0.98 # Define uma leve transparência para o terminal.
blur = true    # Aplica um efeito de desfoque no fundo da janela (caso suportado pelo compositor do sistema).

# Permite redimensionamento proporcional ao conteúdo.
resize_increments = true

[cursor]
style = { shape = "Beam", blinking = "Always" } # Cursor em barra "|" e piscando sempre
blink_interval = 300                            # Tempo de piscada em milissegundos (padrão: 500ms)
unfocused_hollow = true                         # O cursor fica oco quando a janela perde o foco

[scrolling]
# Define o histórico de rolagem para 10.000 linhas, permitindo maior retrospectiva.
history = 10000

# Ajusta a velocidade da rolagem do terminal.
multiplier = 2
